### ISSUE TITLE
Error during training on Hubble dataset: could not broadcast input array from shape (300,300,3) into shape (300)

### ISSUE THREAD

**Issue by ielbert** [stitchfix/fauxtograph#13]
Running on Mac for Hubble dataset:
$ fauxtograph train ./images ./models/model_name 
Traceback (most recent call last):                                                                                                                                                   
  File "/usr/local/bin/fauxtograph", line 9, in <module>
    load_entry_point('fauxtograph==1.0.2', 'console_scripts', 'fauxtograph')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/fauxtograph/fauxto.py", line 122, in train
    x_all = vae.load_images(file_paths)
  File "/Library/Python/2.7/site-packages/fauxtograph/fauxtograph.py", line 239, in load_images
    x_all = np.array([read(fname) for fname in tqdm.tqdm(filepaths)])
ValueError: could not broadcast input array from shape (300,300,3) into shape (300)

**Comment by ielbert** [comment]
Sorry, I re-downloaded images and now it works.
