### ISSUE TITLE
pip installation on py3 fails

### ISSUE THREAD

**Issue by arahuja** [stitchfix/fauxtograph#17]
Looks like the BeautifulSoup dependency does not work on py3. Is there a reason for this specific BS version as opposed to bs4?

```
pip install fauxtograph
Collecting fauxtograph
  Downloading fauxtograph-1.0.3.tar.gz
Collecting chainer==1.6.0 (from fauxtograph)
  Downloading chainer-1.6.0.tar.gz (904kB)
    100% |████████████████████████████████| 905kB 273kB/s
Requirement already satisfied (use --upgrade to upgrade): pillow in ./anaconda/envs/py34/lib/python3.4/site-packages (from fauxtograph)
Collecting joblib (from fauxtograph)
  Downloading joblib-0.9.4-py2.py3-none-any.whl (112kB)
    100% |████████████████████████████████| 114kB 1.7MB/s
Collecting tqdm (from fauxtograph)
  Downloading tqdm-3.8.0-py2.py3-none-any.whl
Collecting BeautifulSoup (from fauxtograph)
  Downloading BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/b1/jbv4n2f56mz8m3hxkdtc51cr0000gn/T/pip-build-9v2hhigl/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
```

**Comment by tjtorres** [comment]
No, I just forgot to update the version to bs4 in the setup file. Thanks for the bug report.

**Comment by waleedka** [comment]
Fixed this and other Python3 issues in this PR: https://github.com/stitchfix/fauxtograph/pull/21

**Comment by ArghyaPal** [comment]
HI,
I am facing the same problem, like @arahuja 

`
pip install fauxtograph
Collecting fauxtograph
  Downloading fauxtograph-1.0.3.tar.gz
Collecting chainer==1.6.0 (from fauxtograph)
  Downloading chainer-1.6.0.tar.gz (904kB)
    100% |████████████████████████████████| 905kB 273kB/s
Requirement already satisfied (use --upgrade to upgrade): pillow in ./anaconda/envs/py34/lib/python3.4/site-packages (from fauxtograph)
Collecting joblib (from fauxtograph)
  Downloading joblib-0.9.4-py2.py3-none-any.whl (112kB)
    100% |████████████████████████████████| 114kB 1.7MB/s
Collecting tqdm (from fauxtograph)
  Downloading tqdm-3.8.0-py2.py3-none-any.whl
Collecting BeautifulSoup (from fauxtograph)
  Downloading BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/b1/jbv4n2f56mz8m3hxkdtc51cr0000gn/T/pip-build-9v2hhigl/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
`

I request @tjtorres  to help.

Regards,
Arghya
