### ISSUE TITLE
A runtime error with PNG images.

### ISSUE THREAD

**Issue by jbwhit** [stitchfix/fauxtograph#8]
I don't know where this error is coming from. I have a tar.gz file here of a few images that I was hoping to train with your program: https://www.dropbox.com/s/zfekwp1cspfj9r2/images.tar.gz?dl=0

```
$ fauxtograph train ./images ./models/model_name
Loading Image Files...
Image Files Loaded!

 Training for 200 epochs.

epoch: 1
  0%|                                          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/jonathan/anaconda/bin/fauxtograph", line 11, in <module>
    sys.exit(fauxtograph())
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/fauxtograph/fauxto.py", line 116, in train
    iae.fit(batch_size=batch, n_epochs=epoch)
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/fauxtograph/fauxtograph.py", line 269, in fit
    r_loss, kl_div, out = self._forward(x_batch)
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/fauxtograph/fauxtograph.py", line 176, in _forward
    encoded = self._encode(batch)
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/fauxtograph/fauxtograph.py", line 162, in _encode
    batch = F.relu(getattr(self.model, 'encode_%i' % i)(batch))
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/chainer/function.py", line 164, in __call__
    self._check_data_type_forward(in_data)
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/chainer/function.py", line 191, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/chainer/functions/linear.py", line 105, in check_type_forward
    type_check.Variable(self.W.shape[1], 'W.shape[1]')),
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/chainer/utils/type_check.py", line 457, in expect
    expr.expect()
  File "/Users/jonathan/anaconda/lib/python2.7/site-packages/chainer/utils/type_check.py", line 428, in expect
    '{0} {1} {2}'.format(left, self.inv, right))
chainer.utils.type_check.InvalidType: Expect: prod(in_types[0].shape[1:]) == W.shape[1]
Actual: 30000 != 22500```

**Comment by tjtorres** [comment]
Right now the package only supports images encoded with RGB channels. The images you supplied have an additional opacity/alpha channel and thus won't work with this implementation. I may change this in a future implementation (or if you'd like I certainly welcome PRs), but for now just preprocess the images to convert them from RGBA to just RGB.

Also, just as a side note: with the number of images in that folder (not sure if that's just a subset of them), you're probably going to run into heavy overfitting unless you turn the KL divergence ratio up.

**Comment by jbwhit** [comment]
OK, cool, this helps as I couldn't decipher the error message.

And to your sidenote: Yes, I limited the images so that it was a manageable download for testing.
