### ISSUE TITLE
Chainer error during training: type mismatch

### ISSUE THREAD

**Issue by ielbert** [stitchfix/fauxtograph#9]
Followed steps outline in the blog. Got an error during training:

> fauxtograph train images/ models/model_out
Loading Image Files...
Image Files Loaded!                                                                                                                                                                  

 Training for 200 epochs. 

epoch: 1
  0%|                                                                                                                                                         | 0/12 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/fauxtograph", line 8, in <module>
    load_entry_point('fauxtograph==0.1.8', 'console_scripts', 'fauxtograph')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/fauxtograph/fauxto.py", line 116, in train
    iae.fit(batch_size=batch, n_epochs=epoch)
  File "/Library/Python/2.7/site-packages/fauxtograph/fauxtograph.py", line 271, in fit
    loss.backward()
  File "/Library/Python/2.7/site-packages/chainer/variable.py", line 171, in backward
    self.grad = numpy.ones_like(self.data)
  File "/Library/Python/2.7/site-packages/chainer/variable.py", line 110, in grad
    % (type(self.data), type(g), error_msg))
TypeError: Type of data and grad mismatch: <type 'numpy.ndarray'> != <type 'numpy.float32'>
This error is occured in two cases. The first case is when the user manually
sets the Variable.grad incorrectly. The second case is when some Function
implementation has a bug.

**Comment by tjtorres** [comment]
This one has me a bit stumped honestly as I haven't be able to reproduce it. However, I just updated to use Chainer 1.6, so any external bugs are likely fixed now. If you're still having issues feel free to continue the conversation.
